In [31]:
import pandas as pd

In [32]:
data = {'Name':['John','Alice','Bob','Eve','Charlie'],
        'Age':[25,30,22,35,28],
        'Gender':['Male','Female','Male','Female','Male'],
        'Salary':[50000,55000,40000,70000,48000]
        }

df = pd.DataFrame(data)
print(df.index)

RangeIndex(start=0, stop=5, step=1)

In [33]:
df.set_index('Name',inplace=True)

In [34]:
row = df.loc['John']
print(row)

Age          25
Gender     Male
Salary    50000
Name: John, dtype: object

In [35]:
df_with_index = df.set_index('Name')
print(df_with_index)

KeyError: "None of ['Name'] are in the columns"

In [ ]:
df = df.reset_index()
print(df)

In [ ]:
row = df_reset.loc['John']
print(row)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('nba.csv')
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sample_df = df.sample(15)

In [ ]:
sample_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
172,James Jones,Cleveland Cavaliers,1.0,SG,35.0,6-8,218.0,Miami (FL),947276.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
181,Joel Anthony,Detroit Pistons,50.0,C,33.0,6-9,245.0,UNLV,2500000.0
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,NaN,947276.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
77,Harrison Barnes,Golden State Warriors,40.0,SF,24.0,6-8,225.0,North Carolina,3873398.0
47,Isaiah Canaan,Philadelphia 76ers,0.0,PG,25.0,6-0,201.0,Murray State,947276.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456.0
394,Jameer Nelson,Denver Nuggets,1.0,PG,34.0,6-0,190.0,Saint Joseph's,4345000.0
337,Marvin Williams,Charlotte Hornets,2.0,PF,29.0,6-9,237.0,North Carolina,7000000.0

In [ ]:
sample_df.sort_index(axis = 0)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,NaN,947276.0
47,Isaiah Canaan,Philadelphia 76ers,0.0,PG,25.0,6-0,201.0,Murray State,947276.0
77,Harrison Barnes,Golden State Warriors,40.0,SF,24.0,6-8,225.0,North Carolina,3873398.0
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
172,James Jones,Cleveland Cavaliers,1.0,SG,35.0,6-8,218.0,Miami (FL),947276.0
181,Joel Anthony,Detroit Pistons,50.0,C,33.0,6-9,245.0,UNLV,2500000.0
337,Marvin Williams,Charlotte Hornets,2.0,PF,29.0,6-9,237.0,North Carolina,7000000.0
394,Jameer Nelson,Denver Nuggets,1.0,PG,34.0,6-0,190.0,Saint Joseph's,4345000.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0

In [ ]:
team_counts = df['Team'].value_counts()
print(team_counts)

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Charlotte Hornets         15
Atlanta Hawks             15
San Antonio Spurs         15
Houston Rockets           15
Dallas Mavericks          15
Indiana Pacers            15
Detroit Pistons           15
Cleveland Cavaliers       15
Chicago Bulls             15
Sacramento Kings          15
Phoenix Suns              15
Los Angeles Lakers        15
Los Angeles Clippers      15
Golden State Warriors     15
Toronto Raptors           15
Philadelphia 76ers        15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [ ]:
avg_salary = df.groupby("Team")['Salary'].mean()
print(avg_salary)

Team
Atlanta Hawks             4.860197e+06
Boston Celtics            4.181505e+06
Brooklyn Nets             3.501898e+06
Charlotte Hornets         5.222728e+06
Chicago Bulls             5.785559e+06
Cleveland Cavaliers       7.642049e+06
Dallas Mavericks          4.746582e+06
Denver Nuggets            4.294424e+06
Detroit Pistons           4.477884e+06
Golden State Warriors     5.924600e+06
Houston Rockets           5.018868e+06
Indiana Pacers            4.450122e+06
Los Angeles Clippers      6.323643e+06
Los Angeles Lakers        4.784695e+06
Memphis Grizzlies         5.467920e+06
Miami Heat                6.347359e+06
Milwaukee Bucks           4.350220e+06
Minnesota Timberwolves    4.593054e+06
New Orleans Pelicans      4.355304e+06
New York Knicks           4.581494e+06
Oklahoma City Thunder     6.251020e+06
Orlando Magic             4.297248e+06
Philadelphia 76ers        2.213778e+06
Phoenix Suns              4.229676e+06
Portland Trail Blazers    3.220121e+06
Sacramento Kings          4.778911e+06
San Antonio Spurs         5.629516e+06
Toronto Raptors           4.741174e+06
Utah Jazz                 4.204006e+06
Washington Wizards        5.088576e+06
Name: Salary, dtype: float64

In [ ]:
postion_dist = df.groupby(['Team','Position']).size().unstack(fill_value=0)
print(postion_dist)

Position                C  PF  PG  SF  SG
Team
Atlanta Hawks           3   4   2   2   4
Boston Celtics          3   3   4   1   4
Brooklyn Nets           2   4   3   0   6
Charlotte Hornets       3   3   3   1   5
Chicago Bulls           2   5   2   2   4
Cleveland Cavaliers     3   2   3   2   5
Dallas Mavericks        3   4   4   2   2
Denver Nuggets          3   2   3   3   4
Detroit Pistons         3   2   4   4   2
Golden State Warriors   3   2   2   5   3
Houston Rockets         2   4   2   3   4
Indiana Pacers          2   4   4   3   2
Los Angeles Clippers    2   3   3   4   3
Los Angeles Lakers      3   4   3   4   1
Memphis Grizzlies       1   6   5   3   3
Miami Heat              1   4   2   5   3
Milwaukee Bucks         2   3   4   3   4
Minnesota Timberwolves  3   4   3   3   1
New Orleans Pelicans    3   3   4   4   5
New York Knicks         2   4   2   4   4
Oklahoma City Thunder   3   3   2   3   4
Orlando Magic           2   4   4   1   3
Philadelphia 76ers      2   5   4   2   2
Phoenix Suns            3   2   4   3   3
Portland Trail Blazers  3   3   2   2   5
Sacramento Kings        3   2   2   4   4
San Antonio Spurs       4   2   3   2   4
Toronto Raptors         3   4   3   3   2
Utah Jazz               3   3   4   3   2
Washington Wizards      3   2   2   4   4

In [ ]:
avg_age = df.groupby('Team')['Age'].mean()
print(avg_age)

Team
Atlanta Hawks             28.200000
Boston Celtics            24.733333
Brooklyn Nets             25.600000
Charlotte Hornets         26.133333
Chicago Bulls             27.400000
Cleveland Cavaliers       29.533333
Dallas Mavericks          29.733333
Denver Nuggets            25.733333
Detroit Pistons           26.200000
Golden State Warriors     27.666667
Houston Rockets           26.866667
Indiana Pacers            26.400000
Los Angeles Clippers      29.466667
Los Angeles Lakers        27.533333
Memphis Grizzlies         28.388889
Miami Heat                28.933333
Milwaukee Bucks           24.562500
Minnesota Timberwolves    26.357143
New Orleans Pelicans      26.894737
New York Knicks           27.000000
Oklahoma City Thunder     27.066667
Orlando Magic             25.071429
Philadelphia 76ers        24.600000
Phoenix Suns              25.866667
Portland Trail Blazers    25.066667
Sacramento Kings          26.800000
San Antonio Spurs         31.600000
Toronto Raptors           26.133333
Utah Jazz                 24.466667
Washington Wizards        27.866667
Name: Age, dtype: float64

In [ ]:
avg_Weight = df.groupby('Team')['Weight'].mean()

print(avg_Weight)

Team
Atlanta Hawks             221.266667
Boston Celtics            219.466667
Brooklyn Nets             215.600000
Charlotte Hornets         220.400000
Chicago Bulls             218.933333
Cleveland Cavaliers       227.866667
Dallas Mavericks          227.000000
Denver Nuggets            217.533333
Detroit Pistons           222.200000
Golden State Warriors     224.600000
Houston Rockets           220.333333
Indiana Pacers            222.266667
Los Angeles Clippers      219.733333
Los Angeles Lakers        227.066667
Memphis Grizzlies         218.000000
Miami Heat                218.400000
Milwaukee Bucks           224.062500
Minnesota Timberwolves    228.642857
New Orleans Pelicans      221.000000
New York Knicks           223.625000
Oklahoma City Thunder     229.400000
Orlando Magic             213.357143
Philadelphia 76ers        222.133333
Phoenix Suns              218.600000
Portland Trail Blazers    218.600000
Sacramento Kings          221.333333
San Antonio Spurs         223.933333
Toronto Raptors           221.800000
Utah Jazz                 220.000000
Washington Wizards        219.000000
Name: Weight, dtype: float64

1. RangeIndex (Default):
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88

2. Int64Index:
        Name  Age  Score
101    Alice   25     85
102      Bob   30     90
103  Charlie   35     88

3. Float64Index:
        Name  Age  Score
1.1    Alice   25     85
2.2      Bob   30     90
3.3  Charlie   35     88

4. DatetimeIndex:
               Name  Age  Score
2024-01-01    Alice   25     85
2024-01-02      Bob   30     90
2024-01-03  Charlie   35     88

5. MultiIndex:
                    Name  Age  Score
Group  Subgroup
Group1 A           Alice   25     85
       B             Bob   30     90
Group2 A         Charlie   35     88